name: Deploy Backend + MySQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Traer el código del repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Desplegar en la VPS usando SSH
      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY_BACKEND }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 158.69.192.184 >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 mortydev@158.69.192.184 "
            cd /home/mortydev/backend-traslado || exit
            git reset --hard
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          "
